server:
  port: 6500
spring:
  security:
    user:
      name: mo1212123
      password: 1
      roles: USER, ADMIN
  jpa:
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/telos
    username: root
    password: wjsansrk
